// site.js — Rendering engine for updates-data.js
// Do not edit this file to add content — edit js/updates-data.js instead.

(function () {

  var MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

  var TYPE_CONFIG = {
    talk:  { label: "Talk",  cls: "badge-talk"  },
    paper: { label: "Paper", cls: "badge-paper" },
    grant: { label: "Grant", cls: "badge-grant" },
    news:  { label: "News",  cls: "badge-news"  }
  };

  function formatDate(dateStr) {
    if (!dateStr) return "";
    var parts = dateStr.split("-");
    var year = parts[0];
    var month = parts[1] ? parseInt(parts[1], 10) - 1 : -1;
    if (month >= 0 && month < 12) return MONTHS[month] + " " + year;
    return year;
  }

  function badge(type) {
    var cfg = TYPE_CONFIG[type] || { label: type, cls: "badge-news" };
    return '<span class="entry-badge ' + cfg.cls + '">' + cfg.label + '</span>';
  }

  function entryHTML(e) {
    var titlePart = e.link
      ? '<a href="' + e.link + '">' + e.title + '</a>'
      : e.title;
    var extra = "";
    if (e.venue) extra += ' <span class="entry-venue">&#8212; ' + e.venue + '</span>';
    if (e.note)  extra += ' <em>(' + e.note + ')</em>';
    if (e.photoLink) extra += ' [<a href="' + e.photoLink + '">Photo</a>]';
    var datePart = ' <span class="entry-date">' + formatDate(e.date) + '</span>';
    return '<li>' + badge(e.type) + ' ' + titlePart + extra + datePart + '</li>';
  }

  function sortByDate(arr) {
    return arr.slice().sort(function(a, b) {
      return (b.date || "").localeCompare(a.date || "");
    });
  }

  // ── Homepage highlights ──────────────────────────────────
  function renderHighlights() {
    var container = document.getElementById("highlights-container");
    if (!container || !window.siteData) return;
    var items = sortByDate(siteData.entries.filter(function(e) { return e.highlight; })).slice(0, 6);
    if (items.length === 0) {
      container.innerHTML = "<p><em>No highlights set yet.</em></p>";
      return;
    }
    var html = '<ul class="highlights-list">';
    items.forEach(function(e) { html += entryHTML(e); });
    html += "</ul>";
    container.innerHTML = html;
  }

  // ── Updates page: upcoming ───────────────────────────────
  function renderUpcoming() {
    var container = document.getElementById("upcoming-container");
    if (!container || !window.siteData) return;
    var items = siteData.upcoming || [];
    if (items.length === 0) {
      container.innerHTML = "<p>No upcoming events listed.</p>";
      return;
    }
    var html = "<ul>";
    items.forEach(function(item) {
      html += "<li>";
      if (item.link) html += '<a href="' + item.link + '">' + item.title + "</a>";
      else html += item.title;
      html += ", " + item.venue + ", " + item.date;
      html += "</li>";
    });
    html += "</ul>";
    container.innerHTML = html;
  }

  // ── Updates page: past entries ───────────────────────────
  var currentFilter = "all";

  function renderEntries(filterType) {
    currentFilter = filterType || "all";
    var container = document.getElementById("entries-container");
    if (!container || !window.siteData) return;

    // Update active filter button
    var buttons = document.querySelectorAll(".filter-btn");
    for (var i = 0; i < buttons.length; i++) {
      buttons[i].classList.toggle("active", buttons[i].dataset.filter === currentFilter);
    }

    var allEntries = sortByDate(siteData.entries);
    var filtered = currentFilter === "all"
      ? allEntries
      : allEntries.filter(function(e) { return e.type === currentFilter; });

    // Group by year descending
    var yearMap = {};
    filtered.forEach(function(e) {
      if (!yearMap[e.year]) yearMap[e.year] = [];
      yearMap[e.year].push(e);
    });
    var years = Object.keys(yearMap).map(Number).sort(function(a, b) { return b - a; });

    if (years.length === 0) {
      container.innerHTML = "<p>No entries for this filter.</p>";
      return;
    }

    var html = "";
    years.forEach(function(year, index) {
      if (index === 0) {
        // Most recent year — no year heading; the page already labels it "Recent Updates"
        html += "<ul>";
      } else {
        // Prior years — display year number as h3
        html += "<h3>" + year + "</h3><ul>";
      }
      yearMap[year].forEach(function(e) { html += entryHTML(e); });
      html += "</ul>";
    });
    container.innerHTML = html;
  }

  // Expose filter function so HTML onclick can call it
  window.setFilter = function(type) { renderEntries(type); };

  // ── Publications page ────────────────────────────────────
  function renderPublications() {
    var container = document.getElementById("publications-container");
    if (!container || !window.siteData) return;

    var papers = sortByDate(siteData.entries.filter(function(e) { return e.type === "paper"; }));

    // Group by year descending
    var yearMap = {};
    papers.forEach(function(p) {
      if (!yearMap[p.year]) yearMap[p.year] = [];
      yearMap[p.year].push(p);
    });
    var years = Object.keys(yearMap).map(Number).sort(function(a, b) { return b - a; });

    var html = "<ul>";
    years.forEach(function(year) {
      yearMap[year].forEach(function(p) {
        var titlePart = p.link
          ? '<a href="' + p.link + '">' + p.title + '</a>'
          : p.title;
        var authorPart = p.authors ? p.authors + ', ' : '';
        html += '<li>' + authorPart + titlePart;
        if (p.venue) html += ', <em>' + p.venue + '</em>';
        html += '.</li>';
      });
    });
    html += "</ul>";
    container.innerHTML = html;
  }

  // ── Run on page load ─────────────────────────────────────
  document.addEventListener("DOMContentLoaded", function () {
    renderHighlights();
    renderUpcoming();
    renderEntries("all");
    renderPublications();
  });

})();
