// site.js — Rendering engine for updates-data.js
// Do not edit this file to add content — edit js/updates-data.js instead.

(function () {
  'use strict';

  const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

  const TYPE_CONFIG = {
    talk:  { label: "Talk",  cls: "badge-talk"  },
    paper: { label: "Paper", cls: "badge-paper" },
    grant: { label: "Grant", cls: "badge-grant" },
    news:  { label: "News",  cls: "badge-news"  }
  };

  function formatDate(dateStr) {
    if (!dateStr) return "";
    const parts = dateStr.split("-");
    const year  = parts[0];
    const month = parts[1] ? parseInt(parts[1], 10) - 1 : -1;
    return (month >= 0 && month < 12) ? MONTHS[month] + " " + year : year;
  }

  function badge(type) {
    const cfg = TYPE_CONFIG[type] || { label: type, cls: "badge-news" };
    return `<span class="entry-badge ${cfg.cls}">${cfg.label}</span>`;
  }

  function extraLinks(e) {
    let s = "";
    if (e.doiLink)   s += ` [<a href="${e.doiLink}">DOI</a>]`;
    if (e.pdfLink)   s += ` [<a href="${e.pdfLink}">PDF</a>]`;
    if (e.arxivLink) s += ` [<a href="${e.arxivLink}">arXiv</a>]`;
    return s;
  }

  function entryHTML(e) {
    const titlePart = e.link ? `<a href="${e.link}">${e.title}</a>` : e.title;
    let extra = "";
    if (e.venue)     extra += ` <span class="entry-venue">&mdash; ${e.venue}</span>`;
    if (e.note)      extra += ` <em>(${e.note})</em>`;
    if (e.photoLink) extra += ` [<a href="${e.photoLink}">Photo</a>]`;
    extra += extraLinks(e);
    const datePart = ` <span class="entry-date">${formatDate(e.date)}</span>`;
    return `<li>${badge(e.type)} ${titlePart}${extra}${datePart}</li>`;
  }

  function sortByDate(arr) {
    return arr.slice().sort((a, b) => (b.date || "").localeCompare(a.date || ""));
  }

  function groupByYear(arr) {
    const map = {};
    arr.forEach(e => {
      if (!map[e.year]) map[e.year] = [];
      map[e.year].push(e);
    });
    return map;
  }

  // ── Homepage highlights ──────────────────────────────────
  function renderHighlights() {
    const container = document.getElementById("highlights-container");
    if (!container || !window.siteData) return;
    const items = sortByDate(siteData.entries.filter(e => e.highlight)).slice(0, 6);
    if (items.length === 0) {
      container.innerHTML = "<p><em>No highlights set yet.</em></p>";
      return;
    }
    container.innerHTML = '<ul class="highlights-list">' + items.map(entryHTML).join("") + "</ul>";
  }

  // ── Updates page: upcoming ───────────────────────────────
  function renderUpcoming() {
    const container = document.getElementById("upcoming-container");
    if (!container || !window.siteData) return;
    const items = siteData.upcoming || [];
    if (items.length === 0) {
      container.innerHTML = "<p>No upcoming events listed.</p>";
      return;
    }
    const rows = items.map(item => {
      const t = item.link ? `<a href="${item.link}">${item.title}</a>` : item.title;
      return `<li>${t}, ${item.venue}, ${item.date}</li>`;
    });
    container.innerHTML = `<ul>${rows.join("")}</ul>`;
  }

  // ── Updates page: past entries ───────────────────────────
  let currentFilter = "all";

  function renderEntries(filterType) {
    currentFilter = filterType || "all";
    const container = document.getElementById("entries-container");
    if (!container || !window.siteData) return;

    document.querySelectorAll(".filter-btn").forEach(btn => {
      btn.classList.toggle("active", btn.dataset.filter === currentFilter);
    });

    const all = sortByDate(siteData.entries.filter(e => e.field !== "numerical"));
    const filtered = currentFilter === "all" ? all : all.filter(e => e.type === currentFilter);

    const yearMap = groupByYear(filtered);
    const years = Object.keys(yearMap).map(Number).sort((a, b) => b - a);

    if (years.length === 0) {
      container.innerHTML = "<p>No entries for this filter.</p>";
      return;
    }

    let html = "";
    years.forEach((year, i) => {
      html += (i === 0 ? "<ul>" : `<h3>${year}</h3><ul>`);
      yearMap[year].forEach(e => { html += entryHTML(e); });
      html += "</ul>";
    });
    container.innerHTML = html;
  }

  // ── Publications page ────────────────────────────────────
  function renderPaperList(papers, container) {
    if (!container || papers.length === 0) return;
    const yearMap = groupByYear(papers);
    const years = Object.keys(yearMap).map(Number).sort((a, b) => b - a);
    let html = "";
    years.forEach(year => {
      html += `<h4 class="pub-year">${year}</h4><ul>`;
      yearMap[year].forEach(p => {
        const titlePart = p.link ? `<a href="${p.link}">${p.title}</a>` : p.title;
        const authorPart = p.authors ? p.authors + ", " : "";
        html += `<li>${authorPart}${titlePart}`;
        if (p.venue) html += `, <em>${p.venue}</em>`;
        html += extraLinks(p);
        html += ".</li>";
      });
      html += "</ul>";
    });
    container.innerHTML = html;
  }

  function renderPublications() {
    if (!window.siteData) return;
    const allPapers = sortByDate(siteData.entries.filter(e => e.type === "paper"));
    renderPaperList(
      allPapers.filter(p => p.field !== "numerical"),
      document.getElementById("publications-container")
    );
    renderPaperList(
      allPapers.filter(p => p.field === "numerical"),
      document.getElementById("publications-numerical-container")
    );
  }

  // ── Automate "last update" date ──────────────────────────
  function renderLastUpdate() {
    const el = document.getElementById("last-update-date");
    if (!el || !window.siteData) return;
    const latest = sortByDate(siteData.entries)[0];
    if (latest) el.textContent = formatDate(latest.date);
  }

  // ── Active nav for project pages ─────────────────────────
  function setActiveNav() {
    if (!/\/Project_[^/]+\.html/.test(window.location.pathname)) return;
    document.querySelectorAll("#menu a").forEach(a => {
      if (a.getAttribute("href") === "research.html") {
        a.parentElement.classList.add("current");
      }
    });
  }

  // ── Back-to-top button ───────────────────────────────────
  function setupBackToTop() {
    const btn = document.getElementById("back-to-top");
    if (!btn) return;
    window.addEventListener("scroll", () => {
      btn.classList.toggle("visible", window.scrollY > 400);
    });
    btn.addEventListener("click", e => {
      e.preventDefault();
      window.scrollTo({ top: 0, behavior: "smooth" });
    });
  }

  // ── Filter button event delegation ───────────────────────
  function setupFilterButtons() {
    const bar = document.querySelector(".filter-bar");
    if (!bar) return;
    bar.addEventListener("click", e => {
      if (e.target.matches(".filter-btn")) renderEntries(e.target.dataset.filter);
    });
  }

  // ── Run on page load ─────────────────────────────────────
  document.addEventListener("DOMContentLoaded", function () {
    renderHighlights();
    renderUpcoming();
    renderEntries("all");
    renderPublications();
    renderLastUpdate();
    setActiveNav();
    setupBackToTop();
    setupFilterButtons();
  });

})();
